services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: snippetbox
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass12345
      MYSQL_ROOT_PASSWORD: root12345
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:


  